### ISSUE TITLE
Available enchants change simply by picking up item

### ISSUE THREAD

**Issue by Aceplante2** [Fuzss/easymagic#26]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

1.18.2

### Notes (Required)

Lets say I place a sword in an enchanting table and it offers sharpness 1, unbreaking 1, and sharpness 2. For some reason, if I take the sword back then place it in again, now there are three completely different enchantments which for me makes the mod op and unusable becuase you can reroll until you get exactly what you want?

And no, it does not happen anymore if I disable your mod.

**Comment by Fuzss** [comment]
That is intentional, the reroll button was added for 1.19+ only. The behavior in <1.19 versions is simply a vanilla mechanic from before Minecraft 1.8 that is restored.

There is a server config option in the 1.18 version though where you need to click the book (the animated one above the item/lapis slots) for rerolling with a cost, similar to the dedicated button in the 1.19 versions. You will see a tooltip telling you the costs when it is enabled. In that case taking out the item will no longer cause a reroll.

**Comment by Aceplante2** [comment]
Okay thank you ill try that!
